# gen_unit_requirements.rb - what each land unit costs in commodities.
#
#
# Whether a unit carries a firearm is taken from unit_stats_land's
# primary_missile_weapon rather than guessed from the class name: the shipped
# values are musket (143), carbine (28), rifle (8), plus musket_double,
# rifle_screw_breech and rifle_air - against bow (23), tomahawk (16) and
# chakkar (1), which are NOT firearms and must not consume muskets.
#
# "Above militia" is by unit CLASS. Militia, mobs, irregulars, berserkers and
# war elephants are raised from the population and turn out in their own
# clothes; line, elite, light, grenadier, skirmisher, dragoon, cavalry,
# artillery and general units are uniformed regulars.
#
# THE NUMBERS ARE LARGE ON PURPOSE. A line regiment is ~154 men, so it costs
# ~154 muskets and ~154 uniforms. That is the point of the request, and it is
# what forces the production side to be sized in hundreds per turn rather than
# the dozen-per-turn the chain shipped with. See docs/CHAIN_BALANCE.md for the
# arithmetic that follows from it.
#
# Output: a Lua table the ESE script reads, plus a CSV for eyeballing.
#
# Usage
#   ruby gen_unit_requirements.rb --units <units.csv> --stats <stats.csv>
#                                 [--lua F] [--csv F]

require_relative "../../../empire_paths"

def opt(n, d = nil)
  i = ARGV.index("--#{n}")
  i && ARGV[i + 1] ? ARGV[i + 1] : d
end
units_csv = opt("units")
stats_csv = opt("stats")
lua_out   = opt("lua", File.join(EMPIRE.game, "EmpireScriptExtender/lua/production chains/unit_costs.lua"))
csv_out   = opt("csv")
abort "usage: gen_unit_requirements.rb --units <csv> --stats <csv>" unless units_csv && stats_csv

require "csv"

FIREARMS = %w[musket musket_double carbine rifle rifle_screw_breech rifle_air].freeze

# Classes that turn out in issued uniform. Everything NOT listed here is
# militia-grade and pays no uniform cost.
# Class is the main signal but it is not sufficient: `episodic_2_colonial_
# militia` is classed infantry_skirmishers and was being charged 160 uniforms.
# `armed_citizenry` is no help - it is set only on infantry_mob (20 of 28), not
# across the militia-grade classes - so these are caught by name.
MILITIA_NAMED = /militia|peasant|rabble|levy|fodder|conscript/i

REGULAR = %w[
  infantry_line infantry_elite infantry_light infantry_skirmishers
  infantry_grenadiers dragoons
  cavalry_heavy cavalry_light cavalry_standard cavalry_lancers
  cavalry_missile cavalry_camels
  artillery_foot artillery_horse artillery_fixed
  general
].freeze

stats = {}
CSV.foreach(stats_csv, headers: true) do |r|
  stats[r["key"]] = {
    men:  r["men"].to_i,
    guns: r["guns"].to_i,
    wpn:  r["primary_missile_weapon"].to_s,
  }
end

rows = []
CSV.foreach(units_csv, headers: true) do |r|
  st = stats[r["key"]]
  next unless st                       # 113 of 518 units have no land stats (naval etc.)
  men  = st[:men]
  next if men <= 1                     # single-entity oddities, not formations

  firearm = FIREARMS.include?(st[:wpn])
  militia_named = "#{r['key']} #{r['on_screen_name']}" =~ MILITIA_NAMED
  regular = REGULAR.include?(r["class"].to_s) && !militia_named

  need = {}
  need["res_muskets"]     = men       if firearm
  need["res_ammunition"]  = men       if firearm
  need["res_uniforms"]    = men       if regular
  need["res_cannon"]      = st[:guns] if st[:guns] > 0
  next if need.empty?

  rows << { key: r["key"], name: r["on_screen_name"], cls: r["class"], men: men,
            guns: st[:guns], wpn: st[:wpn], regular: regular, need: need }
end

rows.sort_by! { |x| x[:key] }

# ---- Lua ------------------------------------------------------------------
lua = []
lua << "-- unit_costs.lua - GENERATED by gen_unit_requirements.rb, do not edit."
lua << "-- What each land unit consumes when recruited. See the generator for"
lua << "-- the rules; the short version is muskets and ammunition per man for"
lua << "-- firearm units, uniforms per man for everything above militia, and"
lua << "-- one cannon per gun."
lua << "unit_costs = {"
rows.each do |r|
  parts = r[:need].map { |k, v| "#{k}=#{v}" }.join(", ")
  lua << format("  [%-44s = { %s },", "\"#{r[:key]}\"]", parts)
end
lua << "}"
lua << ""
lua << "-- #{rows.size} units carry a cost."
File.write(lua_out, lua.join("\n") + "\n", mode: "wb")

if csv_out
  CSV.open(csv_out, "wb") do |c|
    c << %w[key name class men guns weapon regular muskets ammunition uniforms cannon]
    rows.each do |r|
      c << [r[:key], r[:name], r[:cls], r[:men], r[:guns], r[:wpn], r[:regular],
            r[:need]["res_muskets"], r[:need]["res_ammunition"],
            r[:need]["res_uniforms"], r[:need]["res_cannon"]]
    end
  end
end

# ---- what this implies for production -------------------------------------
tot = Hash.new(0)
rows.each { |r| r[:need].each { |k, v| tot[k] += v } }
puts "#{rows.size} units costed  ->  #{lua_out}"
puts
puts "per-unit cost, by class (men = muskets = uniforms where they apply):"
rows.group_by { |r| r[:cls] }.sort_by { |_, v| -v.size }.each do |cls, v|
  men = v.map { |x| x[:men] }
  mk  = v.count { |x| x[:need]["res_muskets"] }
  un  = v.count { |x| x[:need]["res_uniforms"] }
  gn  = v.map { |x| x[:guns] }.max
  puts format("  %-22s n=%-4d men %3d-%-3d  firearm %-4d uniformed %-4d  guns<=%d",
              cls, v.size, men.min, men.max, mk, un, gn)
end
puts
# Report the TYPICAL line unit, not the largest. `max_by men` picked Austria's
# 200-man regiment and made the headline example disagree with what the game
# actually shows for almost every faction: 40 of 42 infantry_line rows are 160
# men, which is what the unit card reads in a campaign.
lines = rows.select { |r| r[:cls] == "infantry_line" }
typical_men = lines.map { |r| r[:men] }.tally.max_by { |_, n| n }&.first
line = lines.find { |r| r[:men] == typical_men && r[:key].include?("britain") } ||
       lines.find { |r| r[:men] == typical_men }
puts "a typical line regiment (#{lines.count { |r| r[:men] == typical_men }} of #{lines.size} are #{typical_men} men):"
puts "  #{line[:key]} (#{line[:men]} men) -> " + line[:need].map { |k, v| "#{v} #{k.sub('res_', '')}" }.join(", ")
