-- generated by build_chain_content.ps1 - do not edit by hand
return {
  { out = 'res_steel', qty = 4, inputs = { ['res_iron'] = 2, ['res_coal'] = 3 } },
  { out = 'res_gunpowder', qty = 4, inputs = { ['res_saltpetre'] = 3, ['res_coal'] = 1 } },
  { out = 'res_ammunition', qty = 4, inputs = { ['res_gunpowder'] = 2, ['res_lead'] = 1 } },
  { out = 'res_muskets', qty = 4, inputs = { ['res_steel'] = 4, ['res_timber'] = 1 } },
  { out = 'res_cannon', qty = 1, inputs = { ['res_steel'] = 6, ['res_coal'] = 2 } },
  { out = 'res_textiles', qty = 4, inputs = { ['res_cotton'] = 2, ['res_coal'] = 1 } },
  { out = 'res_uniforms', qty = 4, inputs = { ['res_textiles'] = 4 } },
  { out = 'res_naval_supplies', qty = 4, inputs = { ['res_timber'] = 3, ['res_iron'] = 1 } },
}
