--[[
  chain_sim.lua - production chains for Empire: Total War.

  WHY THIS EXISTS IN LUA AT ALL
    Empire has no native concept of a building CONSUMING a commodity. Effects
    only add. And the demand-driver system that does express one good driving
    another (ddr_cotton_production, ddr_textile_production...) cannot be
    extended: those six names are string literals baked into a fixed array at
    0x014490E4, so a seventh driver would be a key with no code behind it.

    So the engine owns production, pricing, trade and display; this script owns
    STORAGE and CONSUMPTION.

    IT DOES NOT CONVERT. A Foundry already makes steel through
    commodity_prod_steel, so turning iron+coal into steel here as well would
    create every good twice - once in the engine's trade figures and once in
    our stockpile. Instead a produced good OWES its recipe inputs, and the
    stockpile pays them.

    Each turn:
      1. split production into KEPT (up to the player's target) and SOLD
      2. charge the treasury for what was kept - the engine already paid for
         it, so holding it back has to cost what selling would have earned
      3. draw each produced good's recipe inputs from the stockpile, billing
         anything short at an import markup
    See docs/STORAGE_DESIGN.md.

  DESIGN CONSTRAINTS LEARNED THE HARD WAY
    * `pcall` does NOT catch native faults. Engine conditions are C functions
      that dereference their arguments without validating, so a wrong arity or
      a wrong-scoped context is an access violation, not a Lua error. Every
      handler body goes through ESE_Protect, and only verified signatures are
      called.
    * Context is scoped. Reading faction data inside a region-scoped event
      yields silent zeros rather than an error.
    * Persistence WANTS the engine's own save_value/load_value so stockpiles
      travel inside the save. Nothing in the campaign state provides a
      game_interface, so it falls back to a file that does NOT rewind when
      the player loads an earlier save.

  STATUS: runs. Loaded by mod.lua in this folder, ticks on FactionTurnStart, and
  M.selftest() passes. What it does NOT yet have is a production source -
  derive_production() from building counts is phase 1 of the storage design
  and needs a live campaign to confirm the condition signatures.
]]--

local M = {}

-- FALLBACK ONLY. The real list is chain_recipes.lua, generated by
-- build_chain_content.ps1 from chain_manifest.txt so it cannot drift from the
-- DB tables that define the goods; M.load_recipes() below prefers that file.
--
-- `qty` is the BATCH SIZE - how many are produced from the inputs listed.
-- It is not 1. At one musket per one timber a single 160-man regiment would
-- consume more timber than the entire map produces, which is why the manifest
-- moved to batches and why anything reading these must multiply by qty.
M.recipes = {
  { out = 'res_steel',          qty = 4, inputs = { ['res_iron']      = 2, ['res_coal']   = 3 } },
  { out = 'res_gunpowder',      qty = 4, inputs = { ['res_saltpetre'] = 3, ['res_coal']   = 1 } },
  { out = 'res_ammunition',     qty = 4, inputs = { ['res_gunpowder'] = 2, ['res_lead']   = 1 } },
  { out = 'res_muskets',        qty = 4, inputs = { ['res_steel']     = 4, ['res_timber'] = 1 } },
  { out = 'res_cannon',         qty = 1, inputs = { ['res_steel']     = 6, ['res_coal']   = 2 } },
  { out = 'res_textiles',       qty = 4, inputs = { ['res_cotton']    = 2, ['res_coal']   = 1 } },
  { out = 'res_uniforms',       qty = 4, inputs = { ['res_textiles']  = 4 } },
  { out = 'res_naval_supplies', qty = 4, inputs = { ['res_timber']    = 3, ['res_iron']   = 1 } },
}

-- Prefer the generated file, sitting beside this script. Returns the recipes
-- actually in force and says which source won, because silently running the
-- stale fallback is exactly the failure that wastes a playtest.
function M.load_recipes(path)
  local f = io.open(path, "rb")
  if not f then
    return M.recipes, "built-in fallback (" .. path .. " not found)"
  end
  local src = f:read("*a"); f:close()
  local chunk, err = loadstring(src, "chain_recipes")
  if not chunk then
    return M.recipes, "built-in fallback (chain_recipes.lua did not compile: " .. tostring(err) .. ")"
  end
  local ok, t = pcall(chunk)
  if not ok or type(t) ~= "table" or #t == 0 then
    return M.recipes, "built-in fallback (chain_recipes.lua produced no table)"
  end
  M.recipes = t
  return t, "chain_recipes.lua (" .. #t .. " recipes)"
end

-- Recipes must be applied in dependency order: steel before muskets, gunpowder
-- before ammunition. Sorting once at load is cheaper and clearer than assuming
-- the manifest happens to be ordered correctly.
-- Dependency order, and among equally-valid orders the one that respects
-- MANIFEST PRIORITY (earlier in chain_manifest.txt wins).
--
-- Order is not cosmetic: recipes share raw materials and allocation is greedy,
-- so whoever runs first takes what it wants. The first real run picked an
-- arbitrary valid order, naval supplies ran before muskets and ate 48 of 50
-- timber, and the musket works made 8 muskets while 88 steel sat unused.
-- Scanning FORWARD and taking the first ready recipe gives military goods
-- their inputs before naval stores, because that is the manifest's order.
function M.order_recipes(recipes)
  local produced, ordered, remaining = {}, {}, {}
  for i, r in ipairs(recipes) do remaining[i] = r end
  local guard = 0
  while #remaining > 0 and guard < 64 do
    guard = guard + 1
    local progressed = false
    for i = 1, #remaining do
      local r = remaining[i]
      local ready = true
      for input, _ in pairs(r.inputs) do
        -- an input is fine if nothing STILL PENDING produces it: either it is
        -- a raw material, or its producer has already been ordered
        for _, other in ipairs(remaining) do
          if other ~= r and other.out == input then ready = false break end
        end
        if not ready then break end
      end
      if ready then
        table.insert(ordered, r)
        produced[r.out] = true
        table.remove(remaining, i)
        progressed = true
        break        -- restart the scan so priority is re-evaluated each pick
      end
    end
    if not progressed then
      -- a cycle: ship the rest in declaration order rather than looping forever
      for _, r in ipairs(remaining) do table.insert(ordered, r) end
      ESE_Log("[chain] WARNING: recipe cycle detected, " .. #remaining .. " left unordered")
      break
    end
  end
  return ordered
end

-- ---------------------------------------------------------------- stockpiles
-- Keyed per faction so each nation has its own industry.
local function key_for(faction, good) return "chain_" .. faction .. "_" .. good end

-- The engine's own save_value/load_value would be ideal - stockpiles would
-- travel inside the save and survive a reload correctly. But `gi` is only a
-- guess until something is confirmed to provide it: the campaign Lua state
-- exposes events, conditions and a TWELVE-member effect table, and nothing
-- resembling a game_interface. So this uses the engine when it is really
-- there and falls back to a file otherwise, and SAYS WHICH.
--
-- The file fallback desynchronises if the player reloads an earlier save -
-- the stockpile does not rewind with the campaign. That is a real limitation,
-- not a detail; it is acceptable only until save_value is confirmed.
M.store = { kind = "none" }

function M.use_engine_store(gi)
  local ok = pcall(function() return gi:load_value("chain_probe", 0) end)
  if not ok then return false end
  M.store = { kind = "engine", gi = gi }
  return true
end

function M.use_file_store(path)
  local data = {}
  local f = io.open(path, "rb")
  if f then
    local src = f:read("*a"); f:close()
    local chunk = loadstring("return " .. src)
    if chunk then
      local good, t = pcall(chunk)
      if good and type(t) == "table" then data = t end
    end
  end
  M.store = { kind = "file", path = path, data = data, dirty = false }
  return true
end

function M.flush()
  local s = M.store
  if s.kind ~= "file" or not s.dirty then return end
  local parts = { "{" }
  local keys = {}
  for k in pairs(s.data) do table.insert(keys, k) end
  table.sort(keys)
  for _, k in ipairs(keys) do
    -- NEVER write a target_ key here. Targets are owned by the UI state and
    -- live in chain_targets.lua; an old chain_stock.lua may still carry some,
    -- and rewriting them from this stale copy is precisely the clobber the
    -- two-file split exists to prevent. Dropping them here also migrates an
    -- existing file the first time it is written.
    if string.sub(k, 1, 7) ~= "target_" then
      table.insert(parts, string.format("  [%q] = %d,", k, s.data[k]))
    end
  end
  table.insert(parts, "}")
  local f = io.open(s.path, "wb")
  if f then f:write(table.concat(parts, "\n")); f:close(); s.dirty = false end
end

function M.get_stock(gi, faction, good)
  local s, k = M.store, key_for(faction, good)
  if s.kind == "engine" then
    local ok, v = pcall(function() return s.gi:load_value(k, 0) end)
    if ok and type(v) == "number" then return v end
    return 0
  elseif s.kind == "file" then
    return s.data[k] or 0
  end
  return 0
end

function M.set_stock(gi, faction, good, n)
  if n < 0 then n = 0 end
  n = math.floor(n)
  local s, k = M.store, key_for(faction, good)
  if s.kind == "engine" then
    pcall(function() s.gi:save_value(k, n) end)
  elseif s.kind == "file" then
    s.data[k] = n
    s.dirty = true
  end
end

-- ------------------------------------------------- production from buildings
-- No Lua condition returns a commodity QUANTITY - of 279, the only ones that
-- mention commodities or resources are boolean. So production is DERIVED:
-- ask the engine which chain buildings we own, and look their output up in
-- chain_buildings.lua, generated from the same manifest that created them.
-- That beats reading engine memory: no addresses, survives a patch, and it
-- cannot drift from the buildings actually shipped.
M.buildings = {}

function M.load_buildings(path)
  local f = io.open(path, "rb")
  if not f then return nil, "chain_buildings.lua not found at " .. path end
  local src = f:read("*a"); f:close()
  local chunk, err = loadstring(src, "chain_buildings")
  if not chunk then return nil, "chain_buildings.lua did not compile: " .. tostring(err) end
  local ok, t = pcall(chunk)
  if not ok or type(t) ~= "table" then return nil, "chain_buildings.lua produced no table" end
  M.buildings = t
  local n = 0
  for _ in pairs(t) do n = n + 1 end
  return t, n .. " building levels"
end

-- Baseline prices, for costing reserves and imports. The engine's CURRENT
-- price moves with supply and demand but is only reachable from the UI state
-- (trade_info.prices); the campaign state has no price condition. Baseline is
-- the honest approximation and it is what the DB seeds the market with.
M.prices = {}

function M.load_prices(path)
  local f = io.open(path, "rb")
  if not f then return nil, "chain_prices.lua not found at " .. path end
  local src = f:read("*a"); f:close()
  local chunk, err = loadstring(src, "chain_prices")
  if not chunk then return nil, "chain_prices.lua did not compile: " .. tostring(err) end
  local ok, t = pcall(chunk)
  if not ok or type(t) ~= "table" then return nil, "chain_prices.lua produced no table" end
  M.prices = t
  local n = 0
  for _ in pairs(t) do n = n + 1 end
  return t, n .. " prices"
end

-- WHICH SIGNATURE? These are native C functions that dereference their
-- arguments without validating, so a wrong arity or a wrongly-scoped context
-- is an ACCESS VIOLATION that pcall cannot catch - only ESE_Protect can.
-- So we never guess: probe once, in a real campaign, one call at a time, and
-- record what actually worked.
M.sig = nil   -- { fn = <name>, form = "key_ctx" | "region_key_ctx" }

local function protected(fn)
  if type(ESE_Protect) == "function" then
    return ESE_Protect(fn) == "true"
  end
  local ok = pcall(fn)
  return ok
end

-- THE SIGNATURE IS KNOWN. It was recovered statically from Empire.exe rather
-- than by trying calls in a live campaign - tools/dump_conditions.ps1 walks
-- back from every `call 00D1F870` registration and reads the pushed name,
-- usage, parameter documentation and implementing function:
--
--   0086E700  RegionSlotBuildingTypeCount("barracks")
--             Counts the number of buildings in the region slots in the
--             region of the specified type
--             "The key of the building level you are querying from the
--              building_levels table"
--
-- So the argument is a building_levels key (our own level names qualify) and
-- the result is a COUNT, which is what production wants. Region-scoped, so
-- RegionTurnStart is the right event.
--
-- Do NOT go back to probing. A live probe cost a campaign turn and a crash:
-- it called four candidates as fn(key, context), and FactionBuildingExists
-- actually takes THREE - (faction_key, building_level_key, context) - so it
-- received `context` where a string was due and the lookup dereferenced null
-- at 00D0AD03. Wrong ARITY, not a wrong key or scope.
M.sig = { fn = "RegionSlotBuildingTypeCount", form = "key_ctx" }

-- Per-condition argument shapes, so the probe below can never again call one
-- with the wrong number of arguments. Anything not listed here is not probed.
M.SIG_CANDIDATES = {
  { fn = "RegionSlotBuildingTypeCount",  form = "key_ctx" },
  { fn = "RegionSlotBuildingTypeExists", form = "key_ctx" },
  { fn = "BuildingTypeExistsAtSlot",     form = "key_ctx" },
  { fn = "BuildingTypeExistsAtSettlement", form = "key_ctx" },
  -- FactionBuildingExists is deliberately ABSENT: it needs a faction key
  -- first, and calling it with our shape is what crashed the game.
}

-- Returns a human-readable report AND sets M.sig if one form worked.
function M.probe_signatures(context, level, region)
  level = level or "small_coal_mine"
  local lines = { "probing building-count conditions with level=" .. tostring(level) }
  -- NOT FAULTING IS NOT THE SAME AS WORKING. A call returning nil has told us
  -- nothing, and accepting it would set M.sig, unblock accumulate_region and
  -- yield zero production for ever - a false positive indistinguishable from
  -- success. Only a boolean or a number counts as an answer.
  local function usable(v) return type(v) == "boolean" or type(v) == "number" end

  -- ONLY the declared form is ever called. The candidate list carries each
  -- condition's argument shape, so this cannot invent a call the engine does
  -- not accept - which is precisely how the last probe killed the process.
  for _, cand in ipairs(M.SIG_CANDIDATES) do
    local name, form = cand.fn, cand.form
    local fn = conditions and conditions[name]
    if type(fn) ~= "function" then
      lines[#lines + 1] = "  " .. name .. " : ABSENT"
    elseif form ~= "key_ctx" then
      lines[#lines + 1] = "  " .. name .. " : form '" .. tostring(form) .. "' not probeable here"
    else
      local got
      local ok1 = protected(function() got = fn(level, context) end)
      if ok1 then
        lines[#lines + 1] = string.format("  %s(level, context) -> %s (%s)%s",
          name, tostring(got), type(got), usable(got) and "" or "  <- unusable")
        if not M.sig and usable(got) then M.sig = { fn = name, form = form } end
      else
        lines[#lines + 1] = "  " .. name .. "(level, context) FAULTED"
      end
    end
  end
  lines[#lines + 1] = M.sig
    and ("chosen: " .. M.sig.fn .. " / " .. M.sig.form)
    or  "NOTHING WORKED - production cannot be derived yet"
  return table.concat(lines, string.char(10))
end

-- ACCUMULATE PER REGION. RegionTurnStart fires once for EACH region we own,
-- and the Region* conditions only see the region they were handed - so a
-- single call in one region reports that region alone and the faction total
-- is zero-but-plausible, which is worse than an error. The autoexec's
-- existing samplers already use this shape: regions collect, the faction turn
-- consumes.
--
-- `accum` is carried between calls; pass the same table each time and read it
-- at FactionTurnStart.
function M.accumulate_region(context, accum, region)
  accum = accum or {}
  if not M.sig then return accum, "no confirmed signature" end
  local fn = conditions and conditions[M.sig.fn]
  if type(fn) ~= "function" then return accum, "condition missing" end

  -- ONLY OUR OWN REGIONS. RegionTurnStart fires for EVERY region in the
  -- world, not just ours, and the accumulator is reset on the human
  -- FactionTurnStart - so between our turns it sees all 136 regions and
  -- would happily add the AI's factories to our stockpile. Counting the
  -- world's production as ours is a silent, plausible-looking wrong answer,
  -- which is the worst kind.
  local isloc = conditions and conditions.RegionIsLocal
  if type(isloc) == "function" then
    local mine
    if not protected(function() mine = isloc(context) end) then
      return accum, "RegionIsLocal faulted"
    end
    if mine ~= true then return accum, "not our region" end
  end
  -- HONOUR THE CONFIRMED FORM. The probe records whether the working shape
  -- was fn(level, context) or fn(region, level, context), and calling the
  -- other one is not a no-op: it hands the engine a building key where it
  -- expects a region. This used to always call the two-argument form.
  local region_first = (M.sig.form == "region_key_ctx")
  if region_first and region == nil then
    return accum, "signature needs a region and none was passed"
  end
  local found = 0
  for level, info in pairs(M.buildings) do
    local got
    if protected(function()
         if region_first then got = fn(region, level, context)
         else got = fn(level, context) end
       end) then
      if got == true then got = 1 end
      if type(got) == "number" and got > 0 then
        accum[info.com] = (accum[info.com] or 0) + info.out * got
        found = found + 1
      end
    end
  end
  return accum, found
end

-- produced[good] = units, summed over every chain building we own.
-- `regions` is optional; with a confirmed region-scoped signature it is the
-- list of our regions, otherwise the faction-wide form is used.
-- TRACE EVERY KEY BEFORE ASKING ABOUT IT.
--
-- RegionSlotBuildingTypeExists does NOT validate its key: given a building
-- level the engine does not know, it dereferences null (mov eax,[ecx] with
-- ECX=0 at static 0086E8C6). ESE_Protect catches that fault, but the process
-- died shortly afterwards anyway at a second, unguarded site - so a caught
-- native fault is NOT a safe outcome, only a survivable one.
--
-- ese_log flushes per line, so writing the key first means the last line in
-- the log after a crash NAMES the key that did it.
M.trace = false

function M.derive_production(context, regions)
  if not M.sig then return {}, "no confirmed signature - run M.probe_signatures first" end
  local fn = conditions and conditions[M.sig.fn]
  if type(fn) ~= "function" then return {}, "condition " .. M.sig.fn .. " vanished" end

  local produced, counted = {}, 0
  local trace = M.trace and type(ESE_Log) == "function"
  local function add(level, info, n)
    if not n then return end
    if n == true then n = 1 end
    if type(n) ~= "number" or n <= 0 then return end
    produced[info.com] = (produced[info.com] or 0) + info.out * n
    counted = counted + 1
  end

  for level, info in pairs(M.buildings) do
    if trace then ESE_Log("[chain] asking about " .. level) end
    if M.sig.form == "key_ctx" then
      local got
      if protected(function() got = fn(level, context) end) then add(level, info, got)
      elseif trace then ESE_Log("[chain] FAULTED on " .. level) end
    else
      for _, region in ipairs(regions or {}) do
        local got
        if protected(function() got = fn(region, level, context) end) then add(level, info, got) end
      end
    end
  end
  return produced, counted .. " producing building(s)"
end

-- ------------------------------------------------------------------- targets
-- `target` is how many units of a good to hold back before releasing any to
-- trade. One number per good is the whole control surface: below it you keep
-- what you make, at or above it everything flows to trade. 0 = sell all,
-- which is vanilla behaviour and the default.
--
-- TARGETS LIVE IN THEIR OWN FILE, and that is not tidiness - it is required.
-- Targets are set from the Stock Controls TAB, which runs in the UI lua_State;
-- stock is written here, in the CAMPAIGN state. The two cannot call each
-- other, so they share through files. But `M.flush()` rewrites chain_stock.lua
-- WHOLESALE from `M.store.data`, a copy loaded once at startup - so a target
-- the UI wrote mid-turn would be silently erased by the next end-of-turn
-- flush. The click would appear to work, then quietly undo itself.
--
-- One writer per file removes the race entirely:
--     chain_stock.lua    campaign writes, UI reads
--     chain_targets.lua  UI writes,       campaign reads (re-read every turn)
local function tkey(faction, good) return "target_" .. faction .. "_" .. good end

M.targets = { path = nil, data = {} }

function M.use_target_file(path)
  M.targets = { path = path, data = {} }
  M.reload_targets()
  return true
end

-- Re-read from disk. Called at the top of every turn, so a click made while
-- the campaign state was idle is picked up. It is ~23 keys; the cost is noise.
function M.reload_targets()
  local t = {}
  if M.targets.path then
    local f = io.open(M.targets.path, "rb")
    if f then
      local src = f:read("*a"); f:close()
      local chunk = loadstring("return " .. src)
      if chunk then
        local ok, v = pcall(chunk)
        if ok and type(v) == "table" then t = v end
      end
    end
  end
  M.targets.data = t
  return t
end

-- A good is stocked only when its Stock Controls checkbox is ticked. The flag
-- is authoritative: an unticked box means sell everything, whatever target is
-- remembered alongside it, so unticking never loses the number.
local function onkey(faction, good) return "stockon_" .. faction .. "_" .. good end

function M.is_stocking(faction, good)
  return (M.targets.data[onkey(faction, good)] or 0) ~= 0
end

function M.get_target(faction, good)
  if not M.is_stocking(faction, good) then return 0 end
  return M.targets.data[tkey(faction, good)] or 0
end

-- The campaign side rarely sets a target (the UI owns them), but when it does
-- it must write through immediately rather than defer to flush - otherwise it
-- would be writing the UI's file from stale memory, which is the exact bug
-- this split exists to prevent.
function M.set_target(faction, good, n)
  if n < 0 then n = 0 end
  n = math.floor(n)
  M.targets.data[tkey(faction, good)] = n
  -- Keep the flag consistent with the number, or setting a target from the
  -- CLI would write a value that is_stocking() then ignores - the setting
  -- would appear to take and do nothing.
  M.targets.data[onkey(faction, good)] = (n > 0) and 1 or 0
  if not M.targets.path then return end
  local parts, keys = { "{" }, {}
  for k in pairs(M.targets.data) do table.insert(keys, k) end
  table.sort(keys)
  for _, k in ipairs(keys) do
    table.insert(parts, string.format("  [%q] = %d,", k, M.targets.data[k]))
  end
  table.insert(parts, "}")
  local f = io.open(M.targets.path, "wb")
  if f then f:write(table.concat(parts, "\n")); f:close() end
end

-- The presets the World Market panel cycles through on click.
M.TARGET_STEPS = { 0, 100, 500, 2000 }

function M.cycle_target(faction, good)
  local cur = M.get_target(faction, good)
  local nxt = M.TARGET_STEPS[1]
  for i, v in ipairs(M.TARGET_STEPS) do
    if v == cur then nxt = M.TARGET_STEPS[(i % #M.TARGET_STEPS) + 1] break end
  end
  M.set_target(faction, good, nxt)
  return nxt
end

-- ---------------------------------------------------------------- allocation
-- Split this turn's production into what is kept and what goes to trade.
-- Pure: no engine calls, so the selftest can check it.
function M.allocate(produced, stock, targets)
  local reserve, export = {}, {}
  for good, n in pairs(produced or {}) do
    local have = stock[good] or 0
    local want = (targets[good] or 0) - have
    if want < 0 then want = 0 end
    local keep = n < want and n or want
    if keep > 0 then reserve[good] = keep end
    if n - keep > 0 then export[good] = n - keep end
  end
  return reserve, export
end

-- -------------------------------------------------------------- obligations
-- A recipe is NOT production. The engine already made the steel via
-- commodity_prod_steel; if this converted iron+coal into steel as well, every
-- foundry would create it twice. So a produced good OWES its recipe inputs,
-- whether or not the output was sold.
-- Pure, for the same reason as allocate.
function M.obligations(produced, recipes)
  local need = {}
  for _, r in ipairs(recipes) do
    local n = (produced or {})[r.out]
    if n and n > 0 and r.qty > 0 then
      local batches = math.ceil(n / r.qty)
      for input, per in pairs(r.inputs) do
        need[input] = (need[input] or 0) + per * batches
      end
    end
  end
  return need
end

-- ------------------------------------------------------------------ the tick
-- produced : good -> units the engine made this turn (derived from buildings)
-- prices   : good -> unit price, for costing reserves and shortfalls
-- charge   : function(amount) - negative debits the treasury. Optional, so
--            the whole tick can be exercised without an engine.
--
-- Returns a report: an unexplained shortage reads as a bug, so every number
-- the player sees has to be traceable to a cause.
M.IMPORT_MARKUP = 1.5

function M.run_turn(faction, produced, recipes, prices, charge)
  produced, prices = produced or {}, prices or {}
  -- Pick up anything the Stock Controls tab wrote since the last turn. The UI
  -- state owns that file, so the copy in memory here is always potentially
  -- stale; re-reading is the only way a click takes effect.
  M.reload_targets()
  local report = { kept = {}, sold = {}, used = {}, missing = {},
                   reserve_cost = 0, import_cost = 0 }

  -- gather current stock for every good in play
  local goods, stock = {}, {}
  for g in pairs(produced) do goods[g] = true end
  for _, r in ipairs(recipes) do
    goods[r.out] = true
    for i in pairs(r.inputs) do goods[i] = true end
  end
  local targets = {}
  for g in pairs(goods) do
    stock[g]   = M.get_stock(nil, faction, g)
    targets[g] = M.get_target(faction, g)
  end

  -- 1. keep or sell
  local reserve, export = M.allocate(produced, stock, targets)
  for g, n in pairs(reserve) do
    stock[g] = (stock[g] or 0) + n
    report.kept[g] = n
    report.reserve_cost = report.reserve_cost + n * (prices[g] or 0)
  end
  for g, n in pairs(export) do report.sold[g] = n end

  -- 2. pay what the factories consumed, importing whatever is short
  local need = M.obligations(produced, recipes)
  for g, want in pairs(need) do
    local have = stock[g] or 0
    local take = want < have and want or have
    stock[g] = have - take
    if take > 0 then report.used[g] = take end
    local gap = want - take
    if gap > 0 then
      report.missing[g] = gap
      report.import_cost = report.import_cost + gap * (prices[g] or 0) * M.IMPORT_MARKUP
    end
  end

  -- 3. the money. Reserving costs what selling would have earned; a shortfall
  -- costs what buying it abroad would have.
  local total = report.reserve_cost + report.import_cost
  if charge and total > 0 then pcall(charge, -math.floor(total)) end

  for g, n in pairs(stock) do M.set_stock(nil, faction, g, n) end
  report.stock = stock
  return report
end

-- ------------------------------------------------------------------ reporting
local function list(t, suffix)
  local a = {}
  for good, n in pairs(t or {}) do
    table.insert(a, (good:gsub("^res_", "")) .. " x" .. n .. (suffix or ""))
  end
  table.sort(a)
  return a
end

function M.format_report(faction, r)
  local NL = string.char(10)
  local out = { faction .. " industry:" }
  local kept, sold, used, miss = list(r.kept), list(r.sold), list(r.used), list(r.missing)
  if #kept > 0 then table.insert(out, "  kept    : " .. table.concat(kept, ", ")) end
  if #sold > 0 then table.insert(out, "  sold    : " .. table.concat(sold, ", ")) end
  if #used > 0 then table.insert(out, "  consumed: " .. table.concat(used, ", ")) end
  if #miss > 0 then table.insert(out, "  IMPORTED: " .. table.concat(miss, ", ") ..
                                      "  (bought in - no stock)") end
  if (r.reserve_cost or 0) > 0 or (r.import_cost or 0) > 0 then
    table.insert(out, string.format("  cost    : %d held back, %d imported",
                                    math.floor(r.reserve_cost or 0), math.floor(r.import_cost or 0)))
  end
  if #kept == 0 and #sold == 0 and #used == 0 and #miss == 0 then
    table.insert(out, "  (nothing)")
  end
  return table.concat(out, NL)
end

-- ------------------------------------------------------------------- selftest
-- Runs the arithmetic with no engine calls at all, so the logic can be checked
-- before anything touches a live campaign.
-- Checks INVARIANTS of the new model, not a hardcoded arithmetic answer.
-- (The old test asserted "steel 5" and became a liability the moment recipes
-- gained batch quantities.) For ANY recipe set and any targets:
--   1. allocate: kept + sold == produced, and nothing is kept past target
--   2. obligations: a produced good owes inputs at the batch ratio
--   3. no stock ends negative, and every shortfall is billed
function M.selftest()
  local NL = string.char(10)
  local fails, notes = {}, {}
  local function check(c, m) if not c then table.insert(fails, m) end end

  local recipes = M.order_recipes(M.recipes)

  -- 1. allocation -----------------------------------------------------------
  local produced = { res_iron = 100, res_coal = 100, res_steel = 40, res_muskets = 12 }
  local stock0   = { res_iron = 30 }
  local targets  = { res_iron = 100, res_coal = 0, res_steel = 25 }
  local keep, sell = M.allocate(produced, stock0, targets)
  for g, n in pairs(produced) do
    check((keep[g] or 0) + (sell[g] or 0) == n,
          "allocate: " .. g .. " kept+sold ~= produced")
    check((stock0[g] or 0) + (keep[g] or 0) <= math.max(targets[g] or 0, stock0[g] or 0),
          "allocate: " .. g .. " kept past its target")
  end
  check((keep.res_iron or 0) == 70, "allocate: iron should top up 30 -> 100, got " .. tostring(keep.res_iron))
  check((sell.res_coal or 0) == 100, "allocate: coal target 0 so all 100 should sell")

  -- 2. obligations ----------------------------------------------------------
  local need = M.obligations({ res_steel = 8 }, recipes)   -- steel: 4 from 2 iron + 3 coal
  check(need.res_iron == 4, "obligations: 8 steel should owe 4 iron, got " .. tostring(need.res_iron))
  check(need.res_coal == 6, "obligations: 8 steel should owe 6 coal, got " .. tostring(need.res_coal))

  -- 3. a whole tick against a fake store ------------------------------------
  local fake = {}
  local real_get, real_set, real_store = M.get_stock, M.set_stock, M.store
  M.store = { kind = "test" }
  M.get_stock = function(_, f, g) return fake[f .. g] or 0 end
  M.set_stock = function(_, f, g, n) fake[f .. g] = n end
  local real_tget = M.get_target
  M.get_target = function(_, g) return ({ res_iron = 50, res_coal = 50 })[g] or 0 end

  local charged = 0
  local prices = { res_iron = 10, res_coal = 8, res_steel = 26, res_muskets = 55 }
  local rep = M.run_turn("test",
                         { res_iron = 100, res_coal = 100, res_steel = 40, res_muskets = 12 },
                         recipes, prices, function(n) charged = charged + n end)

  M.get_stock, M.set_stock, M.store, M.get_target = real_get, real_set, real_store, real_tget

  for g, n in pairs(rep.stock) do check(n >= 0, "negative stock: " .. g .. " = " .. n) end
  check(charged < 0, "the tick should have debited the treasury, charged = " .. charged)
  check(math.abs(charged) == math.floor(rep.reserve_cost + rep.import_cost),
        "charge does not match reserve_cost + import_cost")
  -- 40 steel owes 20 iron + 30 coal; 12 muskets owe 12 steel + 3 timber.
  -- Only 50 iron and 50 coal were kept, and no timber at all, so timber MUST
  -- appear as an import rather than silently vanishing.
  check((rep.missing.res_timber or 0) > 0, "timber was never in stock, so it must be imported")
  check((rep.import_cost or 0) > 0, "an import should cost something")

  table.insert(notes, "recipes  : " .. #recipes)
  table.insert(notes, M.format_report("test", rep))
  table.insert(notes, string.format("treasury : %d", charged))
  if #fails == 0 then
    table.insert(notes, "SELFTEST PASS - allocation, obligations and billing all hold")
  else
    table.insert(notes, "SELFTEST FAILED - " .. #fails .. " problem(s):")
    for _, f in ipairs(fails) do table.insert(notes, "  * " .. f) end
  end
  return table.concat(notes, NL), #fails == 0
end
return M
